language: node_js
node_js: 9
before_script:
  - npm install yarn webpack -g
  - cd crx
  - yarn
  - cd ..
  - yarn

script:
  - yarn build
  - cd crx
  - yarn build
  - cd ..

after_success:
  - pwd
  - git commit -a -m "Travis build"
  - git status
  - git push "https://${GH_TOKEN}@${GH_REF}" master:master

cache:
  yarn: true
  webpack: true
  directories:
    - "node_modules"
    - "crx/node_modules"

env:
 global:
   - GH_REF: github.com/jae-jae/Userscript-Plus.git